### ISSUE TITLE
signing commits 

### ISSUE THREAD

**Issue by protocolpolice** [MinBZK/nl-wallet#6]
line: 107 "all commits should be signed using a GPG key" 

question: why care and [exclude] non-pgp, the content of the code speaks for itself?

**Comment by Potherca** [comment]
Bruh, WTF?

**Comment by protocolpolice** [comment]
..lol
 
the magic doesn't happen in the signing, it's what the code does ( ..or doesn't in the wallet's case )
 
you're looking at it from a dev or enduser viewpoint, the attackers won't
 
there's an elephant in the room, digital currency, sidetrack on collision course

**Comment by confiks** [comment]
I'm afraid I don't fully understand your question. This project uses GPG-signed commits in the private version of this repository (which is synced to the public repository roughly every three weeks) to maintain an audit log about who added which who code. We settled on GPG because at the time, SSH-key signed commits were not available yet; they were introduced a few months later.

Feel free to reopen if you have another question.
